FROM ubuntu:focal 

LABEL maintainer="local" 

RUN apt-get update \
	&& apt-get install -y software-properties-common \
	&& apt-get update \
	&& apt-get install -y curl \
	&& apt-get install -y apt-utils \
	&& apt-get install -y libunwind8  \
	&& apt-get install -y locales \
	&& apt-get install -y git \
	&& locale-gen en_US.UTF-8 


RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
	&& apt-get install -y nodejs \
	&& npm install npm@latest -g \
	&& npm install -g autorest@latest 

RUN autorest --go --allow-no-input --v3 --azure-validator --use=@autorest/go@4.0.0-preview.13

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

ENTRYPOINT ["autorest"]