// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package commercialmarketplace

const telemetryInfo = "azsdk-go-commercialmarketplace/v1.0.0"
type AllowedCustomerOperationsEnum string

const (
	AllowedCustomerOperationsEnumRead AllowedCustomerOperationsEnum = "Read"
	AllowedCustomerOperationsEnumUpdate AllowedCustomerOperationsEnum = "Update"
	AllowedCustomerOperationsEnumDelete AllowedCustomerOperationsEnum = "Delete"
)

// PossibleAllowedCustomerOperationsEnumValues returns the possible values for the AllowedCustomerOperationsEnum const type.
func PossibleAllowedCustomerOperationsEnumValues() []AllowedCustomerOperationsEnum {
	return []AllowedCustomerOperationsEnum{	
		AllowedCustomerOperationsEnumRead,
		AllowedCustomerOperationsEnumUpdate,
		AllowedCustomerOperationsEnumDelete,
	}
}

// ToPtr returns a *AllowedCustomerOperationsEnum pointing to the current value.
func (c AllowedCustomerOperationsEnum) ToPtr() *AllowedCustomerOperationsEnum {
	return &c
}

type OperationActionEnum string

const (
	OperationActionEnumUnsubscribe OperationActionEnum = "Unsubscribe"
	OperationActionEnumChangePlan OperationActionEnum = "ChangePlan"
	OperationActionEnumChangeQuantity OperationActionEnum = "ChangeQuantity"
	OperationActionEnumSuspend OperationActionEnum = "Suspend"
	OperationActionEnumReinstate OperationActionEnum = "Reinstate"
)

// PossibleOperationActionEnumValues returns the possible values for the OperationActionEnum const type.
func PossibleOperationActionEnumValues() []OperationActionEnum {
	return []OperationActionEnum{	
		OperationActionEnumUnsubscribe,
		OperationActionEnumChangePlan,
		OperationActionEnumChangeQuantity,
		OperationActionEnumSuspend,
		OperationActionEnumReinstate,
	}
}

// ToPtr returns a *OperationActionEnum pointing to the current value.
func (c OperationActionEnum) ToPtr() *OperationActionEnum {
	return &c
}

type OperationStatusEnum string

const (
	OperationStatusEnumNotStarted OperationStatusEnum = "NotStarted"
	OperationStatusEnumInProgress OperationStatusEnum = "InProgress"
	OperationStatusEnumSucceeded OperationStatusEnum = "Succeeded"
	OperationStatusEnumFailed OperationStatusEnum = "Failed"
	OperationStatusEnumConflict OperationStatusEnum = "Conflict"
)

// PossibleOperationStatusEnumValues returns the possible values for the OperationStatusEnum const type.
func PossibleOperationStatusEnumValues() []OperationStatusEnum {
	return []OperationStatusEnum{	
		OperationStatusEnumNotStarted,
		OperationStatusEnumInProgress,
		OperationStatusEnumSucceeded,
		OperationStatusEnumFailed,
		OperationStatusEnumConflict,
	}
}

// ToPtr returns a *OperationStatusEnum pointing to the current value.
func (c OperationStatusEnum) ToPtr() *OperationStatusEnum {
	return &c
}

// SandboxTypeEnum - Possible Values are None, Csp (Csp sandbox purchase)
type SandboxTypeEnum string

const (
	SandboxTypeEnumNone SandboxTypeEnum = "None"
	SandboxTypeEnumCsp SandboxTypeEnum = "Csp"
)

// PossibleSandboxTypeEnumValues returns the possible values for the SandboxTypeEnum const type.
func PossibleSandboxTypeEnumValues() []SandboxTypeEnum {
	return []SandboxTypeEnum{	
		SandboxTypeEnumNone,
		SandboxTypeEnumCsp,
	}
}

// ToPtr returns a *SandboxTypeEnum pointing to the current value.
func (c SandboxTypeEnum) ToPtr() *SandboxTypeEnum {
	return &c
}

// SessionModeEnum - Dry Run indicates all transactions run as Test-Mode in the commerce stack
type SessionModeEnum string

const (
	SessionModeEnumNone SessionModeEnum = "None"
	SessionModeEnumDryRun SessionModeEnum = "DryRun"
)

// PossibleSessionModeEnumValues returns the possible values for the SessionModeEnum const type.
func PossibleSessionModeEnumValues() []SessionModeEnum {
	return []SessionModeEnum{	
		SessionModeEnumNone,
		SessionModeEnumDryRun,
	}
}

// ToPtr returns a *SessionModeEnum pointing to the current value.
func (c SessionModeEnum) ToPtr() *SessionModeEnum {
	return &c
}

// SubscriptionStatusEnum - Indicates the status of the operation.
type SubscriptionStatusEnum string

const (
	SubscriptionStatusEnumNotStarted SubscriptionStatusEnum = "NotStarted"
	SubscriptionStatusEnumPendingFulfillmentStart SubscriptionStatusEnum = "PendingFulfillmentStart"
	SubscriptionStatusEnumSubscribed SubscriptionStatusEnum = "Subscribed"
	SubscriptionStatusEnumSuspended SubscriptionStatusEnum = "Suspended"
	SubscriptionStatusEnumUnsubscribed SubscriptionStatusEnum = "Unsubscribed"
)

// PossibleSubscriptionStatusEnumValues returns the possible values for the SubscriptionStatusEnum const type.
func PossibleSubscriptionStatusEnumValues() []SubscriptionStatusEnum {
	return []SubscriptionStatusEnum{	
		SubscriptionStatusEnumNotStarted,
		SubscriptionStatusEnumPendingFulfillmentStart,
		SubscriptionStatusEnumSubscribed,
		SubscriptionStatusEnumSuspended,
		SubscriptionStatusEnumUnsubscribed,
	}
}

// ToPtr returns a *SubscriptionStatusEnum pointing to the current value.
func (c SubscriptionStatusEnum) ToPtr() *SubscriptionStatusEnum {
	return &c
}

type TermUnitEnum string

const (
	TermUnitEnumP1M TermUnitEnum = "P1M"
	TermUnitEnumP1Y TermUnitEnum = "P1Y"
)

// PossibleTermUnitEnumValues returns the possible values for the TermUnitEnum const type.
func PossibleTermUnitEnumValues() []TermUnitEnum {
	return []TermUnitEnum{	
		TermUnitEnumP1M,
		TermUnitEnumP1Y,
	}
}

// ToPtr returns a *TermUnitEnum pointing to the current value.
func (c TermUnitEnum) ToPtr() *TermUnitEnum {
	return &c
}

type UpdateOperationStatusEnum string

const (
	UpdateOperationStatusEnumSuccess UpdateOperationStatusEnum = "Success"
	UpdateOperationStatusEnumFailure UpdateOperationStatusEnum = "Failure"
)

// PossibleUpdateOperationStatusEnumValues returns the possible values for the UpdateOperationStatusEnum const type.
func PossibleUpdateOperationStatusEnumValues() []UpdateOperationStatusEnum {
	return []UpdateOperationStatusEnum{	
		UpdateOperationStatusEnumSuccess,
		UpdateOperationStatusEnumFailure,
	}
}

// ToPtr returns a *UpdateOperationStatusEnum pointing to the current value.
func (c UpdateOperationStatusEnum) ToPtr() *UpdateOperationStatusEnum {
	return &c
}



