// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package commercialmarketplace

const telemetryInfo_unused = "azsdk-go-metering/v1.0.0"
// UsageEventStatusEnum - Status of the operation.
type UsageEventStatusEnum string

const (
	UsageEventStatusEnumAccepted UsageEventStatusEnum = "Accepted"
	UsageEventStatusEnumExpired UsageEventStatusEnum = "Expired"
	UsageEventStatusEnumDuplicate UsageEventStatusEnum = "Duplicate"
	UsageEventStatusEnumError UsageEventStatusEnum = "Error"
	UsageEventStatusEnumResourceNotFound UsageEventStatusEnum = "ResourceNotFound"
	UsageEventStatusEnumResourceNotAuthorized UsageEventStatusEnum = "ResourceNotAuthorized"
	UsageEventStatusEnumInvalidDimension UsageEventStatusEnum = "InvalidDimension"
	UsageEventStatusEnumInvalidQuantity UsageEventStatusEnum = "InvalidQuantity"
	UsageEventStatusEnumBadArgument UsageEventStatusEnum = "BadArgument"
)

// PossibleUsageEventStatusEnumValues returns the possible values for the UsageEventStatusEnum const type.
func PossibleUsageEventStatusEnumValues() []UsageEventStatusEnum {
	return []UsageEventStatusEnum{	
		UsageEventStatusEnumAccepted,
		UsageEventStatusEnumExpired,
		UsageEventStatusEnumDuplicate,
		UsageEventStatusEnumError,
		UsageEventStatusEnumResourceNotFound,
		UsageEventStatusEnumResourceNotAuthorized,
		UsageEventStatusEnumInvalidDimension,
		UsageEventStatusEnumInvalidQuantity,
		UsageEventStatusEnumBadArgument,
	}
}

// ToPtr returns a *UsageEventStatusEnum pointing to the current value.
func (c UsageEventStatusEnum) ToPtr() *UsageEventStatusEnum {
	return &c
}



