// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package commercialmarketplace

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"net/http"
	"reflect"
)

// FulfillmentOperationsListSubscriptionsPager provides operations for iterating over paged responses.
type FulfillmentOperationsListSubscriptionsPager struct {
	client *FulfillmentOperationsClient
	current FulfillmentOperationsListSubscriptionsResponse
	err error
	requester func(context.Context) (*azcore.Request, error)
	advancer func(context.Context, FulfillmentOperationsListSubscriptionsResponse) (*azcore.Request, error)
}

// Err returns the last error encountered while paging.
func (p *FulfillmentOperationsListSubscriptionsPager) Err() error {
	return p.err
}

// NextPage returns true if the pager advanced to the next page.
// Returns false if there are no more pages or an error occurred.
func (p *FulfillmentOperationsListSubscriptionsPager) NextPage(ctx context.Context) bool {
	var req *azcore.Request
	var err error
	if !reflect.ValueOf(p.current).IsZero() {
		if p.current.SubscriptionsResponse.NextLink == nil || len(*p.current.SubscriptionsResponse.NextLink) == 0 {
			return false
		}
		req, err = p.advancer(ctx, p.current)
	} else {
		req, err = p.requester(ctx)
	}
	if err != nil {
		p.err = err
		return false
	}
	resp, err := p.client.con.Pipeline().Do(req)
	if err != nil {
		p.err = err
		return false
	}
	if !resp.HasStatusCode(http.StatusOK) {
		p.err = p.client.listSubscriptionsHandleError(resp)
		return false
	}
	result, err := p.client.listSubscriptionsHandleResponse(resp)
	if err != nil {
		p.err = err
		return false
	}
	p.current = result
	return true
}

// PageResponse returns the current FulfillmentOperationsListSubscriptionsResponse page.
func (p *FulfillmentOperationsListSubscriptionsPager) PageResponse() FulfillmentOperationsListSubscriptionsResponse {
	return p.current
}


