// +build go1.13

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package commercialmarketplace

import "net/http"

// MeteringOperationsPostBatchUsageEventResponse contains the response from method MeteringOperations.PostBatchUsageEvent.
type MeteringOperationsPostBatchUsageEventResponse struct {
	MeteringOperationsPostBatchUsageEventResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// MeteringOperationsPostBatchUsageEventResult contains the result from method MeteringOperations.PostBatchUsageEvent.
type MeteringOperationsPostBatchUsageEventResult struct {
	BatchUsageEventOkResponse
}

// MeteringOperationsPostUsageEventResponse contains the response from method MeteringOperations.PostUsageEvent.
type MeteringOperationsPostUsageEventResponse struct {
	MeteringOperationsPostUsageEventResult
	// RawResponse contains the underlying HTTP response.
	RawResponse *http.Response
}

// MeteringOperationsPostUsageEventResult contains the result from method MeteringOperations.PostUsageEvent.
type MeteringOperationsPostUsageEventResult struct {
	UsageEventOkResponse
}


